global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:5000']
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
  - job_name: 'db'
    static_configs:
      - targets: ['db:5432']
  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins:8181']
